name: Update Stratus Docs
on:
  push:
    paths:
      - 'README.md'
    branches:
      - 'master'

jobs:
  saveReadmeFile:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
        with:
          fetch-depth: 0

      - name: upload readme file to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: readme
          path: README.md

  updateReadmeOnStratus:
    runs-on: ubuntu-latest
    needs: saveReadmeFile
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: babanesma/test-docs
          fetch-depth: 0

      - name: download updated readme
        uses: actions/download-artifact@v2
        with:
          name: readme
          path: docs/microservices/test-ms.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: update stratus docs
          title: Update Docs
          body: update stratus docs with new changes in README.md
          branch: update-docs
